title: "Who is Remove Your Media LLC?"
description: "Are they legitimate? And who is Eric Green?"
theme: jekyll-theme-midnight

url: "https://remove-your-media.github.io"
baseurl: "/who-are-theyy"

image: "/embed-icon.png"

plugins:
  - jekyll-seo-tag